### ISSUE TITLE
Maak een assets folder aan!

### ISSUE THREAD

**Issue by KaanKalmi** [smolgeorgie/the-startup-responsive-interactieve-website#1]
![image](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144000125/cfa0beac-f370-47ac-85d4-e328c48b32ac)
Je hebt hier veel images liggen, stop ze allemaal in een assets folder!

[Hier nog een handig artikel i.v.m folder structuur](https://dev.to/noruwa/folder-structure-for-modern-web-applications-4d11#:~:text=The%20assets%20folder%20contains%20all,being%20placed%20inside%20this%20folder.)

**Comment by smolgeorgie** [comment]
Ik heb ze allllleemaal in een assets folder gezet! tis gefixt :)

![image_2024-01-16_222702451](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144005439/0cdc18f3-9ae4-40d2-9298-2f27e33555ec)
