### ISSUE TITLE
'lees meer beschrijving' staat fout

### ISSUE THREAD

**Issue by Vikkeyeftimov** [smolgeorgie/the-startup-responsive-interactieve-website#10]
Ik vind dat je button ''+ lees meer beschrijving'' niet goed staat je button staat boven de omschrijving. bij zo button past het stuk beter als je het daaronder hebt staan. 
![image](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144008940/de499109-9273-45e1-b65b-b83426936858)

**Comment by smolgeorgie** [comment]
fixed

![opera_Qzb9eDPmHx](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144005439/7f8223c3-bb77-43ec-a429-bc921511b92e)
