### ISSUE TITLE
Wat overige punten

### ISSUE THREAD

**Issue by KaanKalmi** [smolgeorgie/the-startup-responsive-interactieve-website#3]
- Voeg meer content toe aan je pagina!!
- Contrast tussen wit en geel in nav is niet goed!

**Comment by smolgeorgie** [comment]
1: het is geen geel, het is ORANJE. 
2. de content komt eraan, het is nog in constructie
3. deze contrast is bekend maar ze hebben verteld dat we deze kleuren moeten gebruiken. huisstijl is huisstijl
