### ISSUE TITLE
Maps als Iframe toevoegen

### ISSUE THREAD

**Issue by Anna-Kyra** [smolgeorgie/the-startup-responsive-interactieve-website#4]
```HTML
<a href="https://www.google.com/maps/place/Themaat,+3455+SM+Utrecht/@52.1157377,5.0000966,15z/data=!3m1!4b1!4m6!3m5!1s0x47c670383ef116fb:0xa6a9493b78ccf6d!8m2!3d52.1157255!4d5.0104178!16zL20vMGNudmhx?entry=ttu"> Haarrijn </a>
```

<img width="1680" alt="Scherm­afbeelding 2024-01-19 om 11 32 10" src="https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144000242/d427f7ee-81c4-4d2c-9b05-f4d6452cacc6">

Je kan als je naar google maps staan de `iframe` ervan kopieëren inplaats van een plaatje.

**Comment by smolgeorgie** [comment]
Ik heb dit geprobeerd, maar ik denk dat mijn button daar te klein voor is! Ik krijg gelijk voorwaarden voor de locatie tevoorschijn. 

Dit is wat ik te zien krijg: 
![agreements-google-maps-button-funda](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/assets/144005439/cd47791b-32b1-488c-96a0-fe731b389cd5)

Was echt een top idee, alleen hij werkt bij mijn design niet ben ik bang. jammer :(
