### ISSUE TITLE
IMG heeft geen alt

### ISSUE THREAD

**Issue by Anna-Kyra** [smolgeorgie/the-startup-responsive-interactieve-website#6]
```HTML
                <img src="assets/villa-image.jpg">
```
[Permalink](https://github.com/smolgeorgie/the-startup-responsive-interactieve-website/blob/5b284d7e6535366fdc6e8094fe822fae4431c370/index.html#L44)

Er is geen `alt` bij je afbeeldingen

**Comment by smolgeorgie** [comment]
complete

```html
                    <img src="assets/villa-image.jpg" alt: "villa afbeelding haarrijn">

```
